/**   Description :   Purpose to create this class is to perform overriding
*
*     Created By  :   Prateek Bhadoria
*
*     Arguments   :   None
*
*     Return      :   void
*
*     Revision log:   V_1.0 - Created  - Prateek Bhadoria - Date-08/07/2022
*                     
* 
**/
public class Overriding2 extends Overriding1 {
    /**   Description :   creating a method
    *
    *     Created By  :   Prateek Bhadoria
    *
    *     Arguments   :   None
    *
    *     Return      :   void
    *
    *     Revision log:   V_1.0 - Created  - Prateek Bhadoria - Date-08/07/2022
    *                     
    * 
    **/ 
    public override void write(){
        system.debug('Overriden has been performed ');
    }
}